<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IRC19RF" failures="0" tests="5" name="testNG.workingWithTestNgDependencies" time="0.024" errors="1" timestamp="2023-12-13T16:31:10 IST" skipped="1">
  <testcase classname="testNG.workingWithTestNgDependencies" name="AmmountTransfer" time="0.000">
    <skipped/>
  </testcase> <!-- AmmountTransfer -->
  <system-out/>
  <testcase classname="testNG.workingWithTestNgDependencies" name="OpenAccount" time="0.016">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testNG.workingWithTestNgDependencies.OpenAccount(workingWithTestNgDependencies.java:9)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- OpenAccount -->
  <system-out/>
  <testcase classname="testNG.workingWithTestNgDependencies" name="UpdateMobileNumber" time="0.004"/>
  <system-out>
    <![CDATA[Mobile number updated]]>
  </system-out>
  <testcase classname="testNG.workingWithTestNgDependencies" name="Addbeneficiary" time="0.002"/>
  <system-out>
    <![CDATA[Added benificiary]]>
  </system-out>
  <testcase classname="testNG.workingWithTestNgDependencies" name="DeleteAccount" time="0.002"/>
  <system-out>
    <![CDATA[Account deleted]]>
  </system-out>
</testsuite> <!-- testNG.workingWithTestNgDependencies -->
